[tool.poetry]
package-mode = false
name = "week1-data-processing-tool"
version = "0.1.0"
description = "Data cleaning and validation tool for MLOps week 1"
authors = ["Yopa Nelly <yopatatchou@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.13.4"
pyyaml = "^6.0.3"
pandas = "<3.0"
typer = "^0.27.0"


[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
black = "^26.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
